layout_spectrum: 1
typography_spectrum: 0
color:
  lightness: 0.3088973
  brandStrength: 0.3603206
  saturation: 1
  rhythmicContrast: 0.5181704
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
name: confessionsofastartup.co.za
